import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
)

function generateTempPassword() {
  return `Temp-${Math.random().toString(36).slice(2)}-${Date.now()}`
}

export async function POST(req) {
  const authHeader = req.headers.get('authorization')

  if (!authHeader?.startsWith('Bearer ')) {
    return NextResponse.json(
      { error: 'Unauthorized. Missing token.' },
      { status: 401 }
    )
  }

  const token = authHeader.replace('Bearer ', '').trim()

  const {
    data: { user: caller },
    error: callerError,
  } = await supabaseAdmin.auth.getUser(token)

  if (callerError || !caller) {
    return NextResponse.json(
      { error: 'Unauthorized. Invalid session.' },
      { status: 401 }
    )
  }

  const { data: callerProfile } = await supabaseAdmin
    .from('profiles')
    .select('role')
    .eq('id', caller.id)
    .maybeSingle()

  if (callerProfile?.role !== 'admin') {
    return NextResponse.json(
      { error: 'Admin access required.' },
      { status: 403 }
    )
  }

  const { leadId } = await req.json()

  if (!leadId) {
    return NextResponse.json(
      { error: 'Lead ID is required.' },
      { status: 400 }
    )
  }

  const { data: lead, error: leadError } = await supabaseAdmin
    .from('leads')
    .select('*')
    .eq('id', leadId)
    .maybeSingle()

  if (leadError || !lead) {
    return NextResponse.json(
      { error: 'Lead not found.' },
      { status: 404 }
    )
  }

  let createdUserId = null
  let tempPassword = null

  const { data: createdUser, error: createError } =
    await supabaseAdmin.auth.admin.createUser({
      email: lead.email,
      password: generateTempPassword(),
      email_confirm: true,
    })

  if (createError) {
    return NextResponse.json(
      { error: createError.message },
      { status: 400 }
    )
  }

  createdUserId = createdUser.user.id
  tempPassword = 'Temporary password was generated by system.'

  await supabaseAdmin.from('profiles').upsert({
    id: createdUserId,
    email: lead.email,
    role: 'user',
    plan: 'free',
    subscription_status: 'inactive',
  })

  await supabaseAdmin
    .from('leads')
    .update({
      status: 'approved',
      approved_at: new Date().toISOString(),
      approved_user_id: createdUserId,
    })
    .eq('id', leadId)

  return NextResponse.json({
    success: true,
    userId: createdUserId,
    email: lead.email,
    message:
      'Lead approved and user created. Ask the user to use forgot password to set their password.',
  })
}